version: '3'

services:
    app:
        build: .
        entrypoint: ./.docker/entrypoint.sh
        container_name: front-nextjs-faq
        ports:
            - 3000:3000
        volumes:
            - .:/home/node/app  
