version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    entrypoint: ./.docker/entrypoint.production.sh
    container_name: front-nextjs-faq
    ports:
      - 80:3000
    volumes:
      - .:/home/node/app
