version: '3'

services:
    app:
        build: .
        entrypoint: ./.docker/entrypoint.sh
        container_name: back-express-faq
        ports:
            - 3333:3333
        volumes:
            - .:/home/node/app