version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    entrypoint: ./.docker/entrypoint.production.sh
    container_name: back-express-faq
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    networks:
      - postgres-compose-network
  db:
    build: ./.docker/postgres
    container_name: db-postgres-faq
    restart: always
    tty: true
    volumes:
      - ./.docker/postgres/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=572600
      - POSTGRES_DB=faqweb
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network
  # pgadmin:
  #     image: dpage/pgadmin4
  #     container_name: pgadmin
  #     tty: true
  #     environment:
  #         - PGADMIN_DEFAULT_EMAIL=admin@user.com
  #         - PGADMIN_DEFAULT_PASSWORD=123456
  #     ports:
  #         - 9090:80
  #     depends_on:
  #     - db
  #     networks:
  #     - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
